import Pedido from '../pedido/Pedido';

const itensPedidos: Pedido[] = [
    {
        id: 1,
        nomeCliente: 'João',
        statusPedido: 'pendente',
        dataPedido: '2024-10-01',
        itensPedidos: {
            nomeProduto: 'Notebook Gamer Acer Nitro 5',
            qntde: 1,
            valorUnitario: 5000,
        },
        valorSubtotal: 5000, 
        valorFrete: 10,
        valorTotal: 5010, 
    },
    {
        id: 2,
        nomeCliente: 'Leticia',
        statusPedido: 'entregue',
        dataPedido: '2024-10-02',
        itensPedidos: {
            nomeProduto: 'Cafeteira Elétrica',
            qntde: 3,
            valorUnitario: 250,
        },
        valorSubtotal: 750, 
        valorFrete: 5,
        valorTotal: 755, 
    },
    {
        id: 3,
        nomeCliente: 'Diogo',
        statusPedido: 'pendente',
        dataPedido: '2024-10-03',
        itensPedidos: {
            nomeProduto: 'Smartphone Samsung Galaxy S21',
            qntde: 2,
            valorUnitario: 3000,
        },
        valorSubtotal: 6000, 
        valorFrete: 8,
        valorTotal: 6008, 
    },
    {
        id: 4,
        nomeCliente: 'Lucas',
        statusPedido: 'pendente',
        dataPedido: '2024-10-04',
        itensPedidos: {
            nomeProduto: 'Tênis Nike Air Max',
            qntde: 4,
            valorUnitario: 600,
        },
        valorSubtotal: 2400, 
        valorFrete: 10,
        valorTotal: 2410, 
    },
    {
        id: 5,
        nomeCliente: 'Ryan',
        statusPedido: 'enviado',
        dataPedido: '2024-10-05',
        itensPedidos: {
            nomeProduto: 'Relógio Smartwatch',
            qntde: 1,
            valorUnitario: 800,
        },
        valorSubtotal: 800, 
        valorFrete: 7,
        valorTotal: 807, 
    },
    {
        id: 6,
        nomeCliente: 'Jean',
        statusPedido: 'entregue',
        dataPedido: '2024-10-06',
        itensPedidos: {
            nomeProduto: 'Aspirador de Pó Robô',
            qntde: 3,
            valorUnitario: 1200,
        },
        valorSubtotal: 3600,
        valorFrete: 15,
        valorTotal: 3615, 
    },
    {
        id: 7,
        nomeCliente: 'Ana Luiza',
        statusPedido: 'enviado',
        dataPedido: '2024-10-07',
        itensPedidos: {
            nomeProduto: 'Câmera DSLR Canon',
            qntde: 8,
            valorUnitario: 3500,
        },
        valorSubtotal: 28000,
        valorFrete: 12,
        valorTotal: 28012,
    },
    {
        id: 8,
        nomeCliente: 'Julia',
        statusPedido: 'entregue',
        dataPedido: '2024-10-08',
        itensPedidos: {
            nomeProduto: 'Mesa de Jantar de Madeira',
            qntde: 2,
            valorUnitario: 2000,
        },
        valorSubtotal: 4000, 
        valorFrete: 20,
        valorTotal: 4020,
    },
];

export default itensPedidos;
